model: 'kins'
network: 'ro_34'
task: 'snake'
resume: True
gpus: (0, )
eval_ep: 2000
train:
    optim: 'adam'
    lr: 0.00001
    milestones: (235, 250, 265)
    gamma: 0.25
    batch_size: 32
    dataset: 'KinsTrain'
    num_workers: 16
    epoch: 280
    scheduler: 'manual'
    gammas: [0.5, 0.1 , 0.3]
test:
    dataset: 'KinsMini'
    batch_size: 1
 

heads: {'ct_hm': 7, 'wh': 2}
segm_or_bbox: 'segm'
